mtp_prototypes/urls.py
from django.shortcuts import render
from django.urls import path, include

urlpatterns = [
    path('', lambda request: render(request, 'index.html'), name='index'),
    path('noms_ops/', include('noms_ops.urls', 'noms_ops')),
]

noms_ops/urls.py
from django.urls import path

from noms_ops.views import CreditView, SenderView, PrisonerView, DisbursementView

app_name = 'noms_ops'
urlpatterns = [
    path('credits/', CreditView.as_view(), name='credits'),
    path('credits/senders/', SenderView.as_view(), name='senders'),
    path('credits/prisoners/', PrisonerView.as_view(axis='credits'), name='prisoners'),

    path('disbursements/', DisbursementView.as_view(), name='disbursements'),
    path('disbursements/prisoners/', PrisonerView.as_view(axis='disbursements'), name='prisoners-disbursements'),
]

mtp_prototypes/templates/index.html
{% extends 'govuk_template.html' %}

{% block inner_content %}
  <h1 class="heading-large">Prisoner money intelligence</h1>
  <ul class="list">
    <li>
      <a class="button" href="{% url 'noms_ops:credits' %}">Credits</a>
    </li>
    <li>
      <a class="button" href="{% url 'noms_ops:senders' %}">Payment sources</a>
    </li>
    <li>
      <a class="button" href="{% url 'noms_ops:prisoners' %}">Prisoners</a>
    </li>
    <li>
      <a class="button" href="{% url 'noms_ops:disbursements' %}">Disbursements</a>
    </li>
    <li>
      <a class="button" href="{% url 'noms_ops:prisoners-disbursements' %}">Prisoners by disbursement [<em>new page</em>]</a>
    </li>
  </ul>
{% endblock %}